apiVersion: v1
kind: List
params:
-   name: user
    value: ecp
-   name: elasticsearchUrl
    value: http://elasticsearch-logging:9200
items:
-   apiVersion: v1
    kind: Service
    metadata:
      name: kibana-{user}
      labels:
        system: kibana-{user}
        k8s-app: kibana-{user}
        kubernetes.io/cluster-service: "true"
        addonmanager.kubernetes.io/mode: Reconcile
        kubernetes.io/name: "Kibana"
    spec:
      type: NodePort
      ports:
      - port: 5601
        protocol: TCP
        targetPort: ui
      selector:
        k8s-app: kibana-{user}

-   apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: kibana-{user}
      labels:
        system: kibana-{user}
        k8s-app: kibana-{user}
        kubernetes.io/cluster-service: "true"
        addonmanager.kubernetes.io/mode: Reconcile
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            system: kibana-{user}
            k8s-app: kibana-{user}
        spec:
          containers:
          - name: kibana
            image: gcr.io/google_containers/kibana:v4.6.1-1
            resources:
              # keep request = limit to keep this container in guaranteed class
              limits:
                cpu: 100m
              requests:
                cpu: 100m
            env:
              - name: "ELASTICSEARCH_URL"
                value: "{elasticsearchUrl}"
              - name: "KIBANA_BASE_URL"
                value: ""
            ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
