apiVersion: v1
kind: List
params:
- name: user
  value: xwh
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: swagger-ui
    labels:
      component: swagger-ui
      version: v3.0.17
      system: swagger-ui
  spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      component: swagger-ui
      version: v3.0.17
      system: swagger-ui

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: swagger-ui
    labels:
      component: swagger-ui
      version: v3.0.17
      system: swagger-ui
  spec:
    replicas: 1
    selector:
      component: swagger-ui
      version: v3.0.17
      system: swagger-ui
    template:
      metadata:
        labels:
          component: swagger-ui
          version: v3.0.17
          system: swagger-ui
      spec:
        containers:
        - image: swaggerapi/swagger-ui:v3.0.17
          name: swagger-ui
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
