###
# swagger-editor - https://github.com/swagger-api/swagger-editor/
#
# Run the swagger-editor service on port 8080
###

FROM    dockerhub.ygsoft.com:5000/ygsoft/httpserver:1.0.0

WORKDIR /easycloud
ADD     ./dist    /easycloud
ADD     ./docker/run.sh   /
RUN     chmod +x /run.sh

ENV KUBERNETES_PROXY http://kube.ygcloud.com:8001

# The default port of the application
EXPOSE  4200

#ENTRYPOINT ["/run.sh"]
