kind: "List"
apiVersion: "v1"
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-master
    namespace: default
    labels:
      app: redis
      role: master
  spec:
    ports:
    - port: 6379
      targetPort: 6379
    selector:
      app: redis
      role: master

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: redis-master
    namespace: default
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: redis
          role: master
      spec:
        containers:
        - name: master
          image: redis:3.2.6
          args: ["--appendonly yes"]
          ports:
          - containerPort: 6379
