apiVersion: v1
kind: List
params:
- name: user
  value: yg
- name: version
  value: "1.0"
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: s-petstore-{user}
    labels:
      component: s-petstore
      system: s-petstore-{user}
  spec:
    template:
      metadata:
        labels:
          component: s-petstore
          system: s-petstore-{user}
      spec:
        containers:
        - name: s-petstore
          image: docker.ygsoft.com/xwh/devops.petstore:{version}
          imagePullPolicy: Always
          ports:
          - containerPort: 9080

- apiVersion: v1
  kind: Service
  metadata:
    name: s-petstore-{user}
    labels:
      component: s-petstore
      system: s-petstore-{user}
  spec:
    ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      component: s-petstore
      system: s-petstore-{user}

- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: s-petstore-{user}
    labels:
      component: s-petstore
      system: s-petstore-{user}
  spec:
    rules:
    - host: s-petstore-{user}.ygcloud.com
      http:
        paths:
        - backend:
            serviceName: s-petstore-{user}
            servicePort: 9080
