apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: devops-jenkin
    labels:
      component: devops.jenkin
      system: devops
  spec:
    template:
      metadata:
        labels:
          component: devops.jenkin
          system: devops
      spec:
        containers:
        - name: devops-jenkin
          image: docker.ygsoft.com/ygsoft/maven-run:1.2
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: "-Xms64m -Xmx512m"
          - name: GROUP_ID
            value: xwh
          - name: ARTIFACT_ID
            value: devops.petstore
#          - name: VERSION
#            value: 1.1
          - name: ARGS
            value:
          ports:
          - containerPort: 9080

- apiVersion: v1
  kind: Service
  metadata:
    name: devops-jenkin
    labels:
      component: devops.jenkin
      system: devops
  spec:
    ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      component: devops.jenkin

- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: devops-jenkin
    labels:
      component: devops.jenkin
      system: devops
  spec:
    rules:
    - host: spring.ygcloud.com
      http:
        paths:
        - backend:
            serviceName: devops-jenkin
            servicePort: 9080
