apiVersion: v1
kind: List
params:
- name: GROUP_ID
  value: xwh
- name: ARTIFACT_ID
  value: devops.petstore
- name: VERSION
  value: "1.0"
- name: SYSTEM
  value: ""
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: {SYSTEM}
    labels:
      component: {ARTIFACT_ID}
      system: {SYSTEM}
  spec:
    template:
      metadata:
        labels:
          component: {ARTIFACT_ID}
          system: {SYSTEM}
      spec:
        containers:
        - name: spring-boot-run
          image: dockerhub.ygsoft.com:5000/ygsoft/spring-boot-run:1.2
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: "-Xms64m -Xmx512m"
          - name: GROUP_ID
            value: {GROUP_ID}
          - name: ARTIFACT_ID
            value: {ARTIFACT_ID}
          - name: VERSION
            value: "{VERSION}"
          - name: ARGS
            value:
          ports:
          - containerPort: 9080

- apiVersion: v1
  kind: Service
  metadata:
    name: {SYSTEM}
    labels:
      component: {ARTIFACT_ID}
      system: {SYSTEM}
  spec:
    ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      component: {ARTIFACT_ID}

- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: {SYSTEM}
    labels:
      component: {ARTIFACT_ID}
      system: {SYSTEM}
  spec:
    rules:
    - host: "{SYSTEM}.ygcloud.com"
      http:
        paths:
        - backend:
            serviceName: {SYSTEM}
            servicePort: 9080
