apiVersion: v1
kind: List
params:
- name: user
  value: xwh
- name: namespace
  value: default
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: wordpress-mysql-{user}
    labels:
      component: wordpress-mysql
      version: 5.7.18
      system: wordpress-{user}
  spec:
    type: NodePort
    ports:
    - port: 3306
      protocol: TCP
    selector:
      component: wordpress-mysql
      version: 5.7.18
      system: wordpress-{user}

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: wordpress-mysql-{user}
    labels:
      component: wordpress-mysql
      version: 5.7.18
      system: wordpress-{user}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          component: wordpress-mysql
          version: 5.7.18
          system: wordpress-{user}
      spec:
        containers:
        - name: mysql
          image: mysql:5.7.18
          args: ["--datadir=/datadir/mysqlnfs", "--user=mysql"]
          ports:
          - containerPort: 3306
          env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
          volumeMounts:
          - mountPath: "/datadir"
            name: "datadir"
          securityContext:
            privileged: true
        volumes:
        - name: "datadir"
          emptyDir: {}

- apiVersion: v1
  kind: Service
  metadata:
    name: wordpress-{user}
    labels:
      component: wordpress
      version: 4.8.0-apache
      system: wordpress-{user}
  spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
      nodePort: 30900
    selector:
      component: wordpress
      version: 4.8.0-apache
      system: wordpress-{user}

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: wordpress-{user}
    labels:
      component: wordpress
      version: 4.8.0-apache
      system: wordpress-{user}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          component: wordpress
          version: 4.8.0-apache
          system: wordpress-{user}
      spec:
        containers:
        - name: wordpress
          image: wordpress:4.8.0-apache
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
          env:
          - name: "WORDPRESS_DB_HOST"
            value: "wordpress-mysql-{user}:3306"
          - name: "WORDPRESS_DB_PASSWORD"
            value: "password"

-   apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress-wordpress-{user}
      namespace: {namespace}
      labels:
        system: wordpress-{user}
    spec:
      rules:
      - host: wordpress-{user}.ygcloud.com
        http:
          paths:
          - backend:
              serviceName: wordpress-{user}
              servicePort: 80

